* Twilio 21 App

A simple twilio-powered version of Blackjack. Call into the app and you can play the card game 21.

* Game Info

- instead of cards, players get a random number from 1 to 10
- dealer starts with one random number
- player starts with the sum of two random numbers
- player can hit or stay
- do not go over 21!
- after you stay, dealer will have option to hit or stay

* Technical Info

** Running the game

You need Flask installed, use =pip install flask=

The server needs to know how to access itself on the internet, so set =HOST= and =PORT= as enviroment variables before running.

example:

#+BEGIN_SRC bash
$ HOST=myserver.com
$ PORT=9000
$ python blackjack.py
#+END_SRC

Or you can make a =.env= file and use something like Honcho or Foreman.

Once the server is running, set your host and port as the Voice URL for one of your twilio numbers. Then call the number on a phone!

** Built With

- Python, Flask, Jinja
- Emacs
- Linode
- TWILIO

* Planned Features

** TODO When player enters incorrect input, echo the instructions again
** TODO the HOST variable in the template should be controlled by an enviroment variable
** TODO the HOST varialbe in the template should build off the PORT enviroment variable
